version: "3.8"

services:
  db:
    image: mysql
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=ayoub
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always

    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ayoub

  smart-back:
    image: smart-back
    container_name: smart-back-app
    build:
      context: ./Smart_Home_back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always

    depends_on:
      db:
        condition: service_healthy
  smart-front:
    image: smart-front
    container_name: smart-front-app
    build:
      context: ./smartHome-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

    depends_on:
      db:
        condition: service_healthy
